### ISSUE TITLE
basket download command shows "ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP" message.

### ISSUE THREAD

**Issue by Baneeishaque** [dbaty/Basket#6]
I am trying to download a Pypi package using basket. but the command shows "**ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP**" message.

My command is : **sudo basket download unittest2**

The response is :

```
Traceback (most recent call last):
  File "/usr/local/bin/basket", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/basket/main.py", line 338, in main
    return basket.cmd_download(argv)
  File "/usr/local/lib/python2.7/dist-packages/basket/main.py", line 220, in cmd_download
    info = self._find_package_name(package)
  File "/usr/local/lib/python2.7/dist-packages/basket/main.py", line 88, in _find_package_name
    for info in self.client.search({'name': query}):
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>


```

but pip download command is working fine for me.

My command and response is : 

pip download unittest2
Collecting unittest2
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 107kB/s 
  Saved ./unittest2-1.1.0-py2.py3-none-any.whl
Collecting argparse (from unittest2)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
  Saved ./argparse-1.4.0-py2.py3-none-any.whl
Collecting traceback2 (from unittest2)
  Downloading traceback2-1.4.0-py2.py3-none-any.whl
  Saved ./traceback2-1.4.0-py2.py3-none-any.whl
Collecting six>=1.4 (from unittest2)
  Downloading six-1.10.0-py2.py3-none-any.whl
  Saved ./six-1.10.0-py2.py3-none-any.whl
Collecting linecache2 (from traceback2->unittest2)
  Downloading linecache2-1.0.0-py2.py3-none-any.whl
  Saved ./linecache2-1.0.0-py2.py3-none-any.whl
Successfully downloaded unittest2 argparse traceback2 six linecache2

I posted a question in stackoverflow and got a working answer, that is...

You have to go into /path-to-python-site-packages/basket/main.py, and edit the following line:

PYPI_ENDPOINT = 'http://pypi.python.org/pypi'
And Change it to "https":

PYPI_ENDPOINT = 'https://pypi.python.org/pypi'
Then your downloads should work. Issue is related to "http" being provided to "xmlrpclib.ServerProxy"

It is Working in my windows python 3 environment, not tested in my Ubuntu python 2 environment. i think it will work after this patch. Please make this change after necessary testing and update Pypi repositories.

The stackoverflow question URL is [Protocol Error on basket download request](http://stackoverflow.com/questions/38946159/protocol-error-on-basket-download-request )

**Comment by dbaty** [comment]
It was already reported in #5. Now fixed on master with c9fff6d562f3649399b74d4cc62e00041db80cee. Thanks for the report.
