### ISSUE TITLE
Basket downloads only the Pypi package, not it's dependencies

### ISSUE THREAD

**Issue by Baneeishaque** [dbaty/Basket#7]
I am using Basket to download Python packages from  PyPI server and store them in a single place so that they can be found by easy_install or pip when offline. but **basket downloads only the Pypi package, not it's dependencies**. So, **while installing package in offline pip fails because of unmet dependencies. Please implement dependency download facility too**.

I am used basket version obtained from Pypi site.

**Comment by dbaty** [comment]
Hi. I could not reproduce the issue. For example:

    $ basket  download sqlalchemy
    Added SQLAlchemy 1.1.0b3.
      -> requires: pymssql, pyodbc, mysqlclient, cx_oracle, psycopg2, pg8000, psycopg2cffi, pymysql
    Added pymssql 2.1.3.
    Added pyodbc 3.0.10.
    Added mysqlclient 1.3.7.
    Added cx_Oracle 5.2.1.
    Added psycopg2 2.6.2.
    Added pg8000 1.10.6.
      -> requires: six
    Added psycopg2cffi 2.7.4.
      -> requires: six, cffi
    Added PyMySQL 0.7.9.
    Added six 1.10.0.
    six is already up to date (1.10.0).
    Added cffi 1.7.0.
      -> requires: pycparser
    Added pycparser 2.14.

 Could you please provide an example of a case where Basket does not download the dependencies of a package?

**Comment by dbaty** [comment]
No news is good news. :)
